Question.create(questions: 'Genre')
Question.create(questions: 'Character Age')
Question.create(questions: 'Character Gender')
Question.create(questions: 'Setting')
Question.create(questions: 'Reading Level')
Question.create(questions: 'Publication Date')
Question.create(questions: 'Violence')
Question.create(questions: 'Award Winner')
Question.create(questions: 'Length')
Question.create(questions: 'Reviews')
Answer.create(drop_down_items: 'Fantasy', question_id: 1)
Answer.create(drop_down_items: 'Science Fiction', question_id: '1')
Answer.create(drop_down_items: 'Realistic Fiction', question_id: '1')
Answer.create(drop_down_items: 'Poetry', question_id: '1')
Answer.create(drop_down_items: 'Graphic Novel', question_id: '1')
Answer.create(drop_down_items: 'YA', question_id: '1')
Answer.create(drop_down_items: 'Classic', question_id: '1')
Answer.create(drop_down_items: 'Historical Fiction', question_id: '1')
Answer.create(drop_down_items: 'Thriller', question_id: '1')
Answer.create(drop_down_items: 'Romance', question_id: '1')
Answer.create(drop_down_items: 'Children', question_id: '1')
Answer.create(drop_down_items: 'Mystery', question_id: '1')
Answer.create(drop_down_items: 'Do not care', question_id: '1')
Answer.create(drop_down_items: '0 - 10', question_id: '2')
Answer.create(drop_down_items: '11 - 15', question_id: '2')
Answer.create(drop_down_items: '16 - 20', question_id: '2')
Answer.create(drop_down_items: '21 - 35', question_id: '2')
Answer.create(drop_down_items: '36 - 50', question_id: '2')
Answer.create(drop_down_items: '51 - 100', question_id: '2')
Answer.create(drop_down_items: 'Female', question_id: '3')
Answer.create(drop_down_items: 'Male', question_id: '3')
Answer.create(drop_down_items: 'Do not care', question_id: '3')
Answer.create(drop_down_items: 'Space', question_id: '4')
Answer.create(drop_down_items: 'Earth', question_id: '4')
Answer.create(drop_down_items: 'Past', question_id: '4')
Answer.create(drop_down_items: 'Present', question_id: '4')
Answer.create(drop_down_items: 'Future', question_id: '4')
Answer.create(drop_down_items: 'Imaginary Location', question_id: '4')
Answer.create(drop_down_items: 'Do not care', question_id: '4')
Answer.create(drop_down_items: 'Grade 1-4', question_id: '5')
Answer.create(drop_down_items: 'Grade 5-8', question_id: '5')
Answer.create(drop_down_items: 'Grade 9-12', question_id: '5')
Answer.create(drop_down_items: 'Adult', question_id: '5')
Answer.create(drop_down_items: 'Do not care', question_id: '5')
Answer.create(drop_down_items: 'Before 2000', question_id: '6')
Answer.create(drop_down_items: '2001 - 2015', question_id: '6')
Answer.create(drop_down_items: '2016 - present', question_id: '6')
Answer.create(drop_down_items: 'Do not care', question_id: '6')
Answer.create(drop_down_items: 'True', question_id: '7')
Answer.create(drop_down_items: 'False', question_id: '7')
Answer.create(drop_down_items: 'True', question_id: '8')
Answer.create(drop_down_items: 'False', question_id: '8')
Answer.create(drop_down_items: '0 - 100 pages', question_id: '9')
Answer.create(drop_down_items: '101 - 300 pages', question_id: '9')
Answer.create(drop_down_items: '301 - 700 pages', question_id: '9')
Answer.create(drop_down_items: 'over 700 pages', question_id: '9')
Answer.create(drop_down_items: 'Do not care', question_id: '9')
Answer.create(drop_down_items: '1 star', question_id: '10')
Answer.create(drop_down_items: '2 stars', question_id: '10')
Answer.create(drop_down_items: '3 stars', question_id: '10')
Answer.create(drop_down_items: '4 stars', question_id: '10')
Answer.create(drop_down_items: '5 stars', question_id: '10')